name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
    
    - name: Build
      uses: hensur/operator-sdk-action
      with:
          image: "example"
          tag: 1.0
          dirPath: "/path/to/build/dockerfile"
